
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    ##http://localhost:8080/h2-console
#    url: jdbc:h2:~/side
    username: sa
    password:
    driver-class-name: org.h2.Driver

  ##jwt.yml 불러오기
  profiles:
    include: jwt
jpa:

  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      #      show_sql: true
      format_sql: true
      use_sql_comment: true
logging.level:
  org.hibernate.SQL: debug

