
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/side
    username: sa
    password:
  ##jwt.yml 불러오기
  profiles:
    include: jwt
jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      #      show_sql: true
      format_sql: true
      use_sql_comment: true
logging.level:
  org.hibernate.SQL: debug
server:
  port: 8008
